### PR TITLE
feat(config): add version control for all configuration files by @lzw…

### PR DESCRIPTION
**Pull request by isthaison**
…655 (#32)

### CODE REVIEW

**Comment by Lzw655** [comment]
Hi @isthaison, is there anything you need my help with?

**Comment by isthaison** [comment]
image
I'm running the demo https://github.com/esp-arduino-libs/ESP32_Display_Panel/tree/master/examples/SquareLine/v8/Porting , but it's getting an error, I'm checking to see if there's any problem. code, right?

**Comment by Lzw655** [comment]
I think the problem is the PSRAM is not initialized correctly. Did you enable the PSRAM in the tools menu?
image

**Comment by isthaison** [comment]
https://github.com/esp-arduino-libs/ESP32_Display_Panel/assets/22739578/155ae0ad-0778-4181-b851-58068c7a62c1

LCD render UI position wrong

**Comment by Lzw655** [comment]
This is the RGB screen drift issue, please refer to the [steps ](https://github.com/esp-arduino-libs/ESP32_Display_Panel?tab=readme-ov-file#how-to-fix-screen-drift-issue-when-driving-rgb-lcd-with-esp32-s3) to solve it.

**Comment by isthaison** [comment]
Has it been changed to the master branch yet?

**Comment by Lzw655** [comment]
Sorry, I didn't understand what you meant. Specifically, which modification are you referring to? And which repository's master branch?

**Comment by isthaison** [comment]
I'm looking to build with platformio :D

**Comment by isthaison** [comment]
[https://github.com/esp-arduino-libs/ESP32_Display_Panel/assets/22739578/25d49ea9-8a41-4a0a-9628-058e026a73bb]()
It's OK.

**Comment by isthaison** [comment]
https://github.com/esp-arduino-libs/ESP32_Display_Panel/assets/22739578/1f8f1412-e184-4b27-82c7-2e1b079d74fb

**Comment by Lzw655** [comment]
Nice!!!

**Comment by isthaison** [comment]
The configuration is quite complicated  :D 
```
[env:ESP-LCD]
platform = espressif32
board = ESP-LCD
framework = arduino
platform_packages = 
	platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git
	platformio/framework-arduinoespressif32-libs@https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-I src
	-D VN=1
	-D ESP32S3=1
lib_deps = 
	https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
	https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/lvgl/lvgl.git#release/v8.3
```

Can I  push example build platform.io?

**Comment by Lzw655** [comment]
Of course! It will be very helpful. Please make a new PR and I will test it soon. Thank you for your contribution.

**Comment by isthaison** [comment]
I had create pull request. You can review it
https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/37

**Pull request closed without merging**
