### PR TITLE
fix(examples): fix `LVGL_PORT_ROTATION_DEGREE` issue

### PR DESCRIPTION
**Pull request by Lzw655**
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/76
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/issues/74
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/issues/83
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/84
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/86
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/issues/85
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/82
* closes https://github.com/esp-arduino-libs/ESP32_Display_Panel/issues/92

### CODE REVIEW

**Comment by Lzw655** [comment]
Hi @lboue, Could you please help me test this PR to see if the related bugs are resolved? Thank you very much.

**Comment by lboue** [comment]
@Lzw655 
I've just done a test with my CrowPanel 7.0 screen. I no longer have any issues compiling this branch `fix_LVGL_PORT_ROTATION_DEGREE_issue`.

**Comment by lboue** [comment]
I am having an issue with GPIO expendant Waveshare_ESP32_S3_Touch_LCD_4_3 board

```
d:\ESP32_Display_Panel-bugfix-fix_LVGL_PORT_ROTATION_DEGREE_issue\libraries\ESP32_Display_Panel\src\ESP_Panel.cpp: In member function 'bool ESP_Panel::init()':
d:\ESP32_Display_Panel-bugfix-fix_LVGL_PORT_ROTATION_DEGREE_issue\libraries\ESP32_Display_Panel\src\ESP_Panel.cpp:446:65: error: 'ESP_PANEL_EXPANDER_HOST' was not declared in this scope; did you mean 'ESP_PANEL_EXPANDER_NAME'?
  446 |         expander_ptr = CREATE_EXPANDER(ESP_PANEL_EXPANDER_NAME, ESP_PANEL_EXPANDER_HOST, ESP_PANEL_EXPANDER_I2C_ADDRESS);
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
d:\ESP32_Display_Panel-bugfix-fix_LVGL_PORT_ROTATION_DEGREE_issue\libraries\ESP32_Display_Panel\src\ESP_Panel.cpp:48:85: note: in definition of macro '_CREATE_EXPANDER'
   48 | #define _CREATE_EXPANDER(name, host_id, address) make_shared<ESP_IOExpander_##name>(host_id, address)
      |                                                                                     ^~~~~~~
d:\ESP32_Display_Panel-bugfix-fix_LVGL_PORT_ROTATION_DEGREE_issue\libraries\ESP32_Display_Panel\src\ESP_Panel.cpp:446:24: note: in expansion of macro 'CREATE_EXPANDER'
  446 |         expander_ptr = CREATE_EXPANDER(ESP_PANEL_EXPANDER_NAME, ESP_PANEL_EXPANDER_HOST, ESP_PANEL_EXPANDER_I2C_ADDRESS);
      |                        ^~~~~~~~~~~~~~~
```

`ESP32_S3_Touch_LCD_4.3.h` Config
```
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////// Please update the following macros to configure the IO expander //////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/* Set to 0 if not using IO Expander */
#define ESP_PANEL_USE_EXPANDER          (1)         // 0/1
#if ESP_PANEL_USE_EXPANDER
/**
 * IO expander name.
 */
#define ESP_PANEL_EXPANDER_NAME         CH422G

/* IO expander Settings */
/**
 * If set to 1, the driver will skip to initialize the corresponding host. Users need to initialize the host in advance.
 * It is useful if other devices use the same host. Please ensure that the host is initialized only once.
 */
#define ESP_PANEL_EXPANDER_SKIP_INIT_HOST       (1)     // 0/1
/* IO expander parameters */
#define ESP_PANEL_EXPANDER_I2C_ADDRESS          (0x24)
#if !ESP_PANEL_EXPANDER_SKIP_INIT_HOST
    #define ESP_PANEL_EXPANDER_HOST_ID          (0)     // Typically set to 0
    #define ESP_PANEL_EXPANDER_I2C_CLK_HZ       (400 * 1000)
                                                        // Typically set to 400K
    #define ESP_PANEL_EXPANDER_I2C_SCL_PULLUP   (0)     // 0/1
    #define ESP_PANEL_EXPANDER_I2C_SDA_PULLUP   (0)     // 0/1
    #define ESP_PANEL_EXPANDER_I2C_IO_SCL       (18)
    #define ESP_PANEL_EXPANDER_I2C_IO_SDA       (8)
#endif
#endif /* ESP_PANEL_USE_EXPANDER */
```

**Comment by Lzw655** [comment]
@lboue Sorry, this issue is indeed a bug in the file `ESP_Panel_Board_Custom.h`. The macro `ESP_PANEL_EXPANDER_HOST_ID` should be placed outside the macro `ESP_PANEL_EXPANDER_SKIP_INIT_HOST`. The correct code is as follows:

```c
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////// Please update the following macros to configure the IO expander //////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/* Set to 0 if not using IO Expander */
#define ESP_PANEL_USE_EXPANDER          (1)         // 0/1
#if ESP_PANEL_USE_EXPANDER
/**
 * IO expander name.
 */
#define ESP_PANEL_EXPANDER_NAME         CH422G

/* IO expander Settings */
/**
 * If set to 1, the driver will skip to initialize the corresponding host. Users need to initialize the host in advance.
 * It is useful if other devices use the same host. Please ensure that the host is initialized only once.
 */
#define ESP_PANEL_EXPANDER_SKIP_INIT_HOST       (1)     // 0/1
/* IO expander parameters */
#define ESP_PANEL_EXPANDER_HOST_ID                  (0)     // Typically set to 0
#define ESP_PANEL_EXPANDER_I2C_ADDRESS          (0x24)
#if !ESP_PANEL_EXPANDER_SKIP_INIT_HOST
    #define ESP_PANEL_EXPANDER_I2C_CLK_HZ       (400 * 1000)
                                                        // Typically set to 400K
    #define ESP_PANEL_EXPANDER_I2C_SCL_PULLUP   (0)     // 0/1
    #define ESP_PANEL_EXPANDER_I2C_SDA_PULLUP   (0)     // 0/1
    #define ESP_PANEL_EXPANDER_I2C_IO_SCL       (18)
    #define ESP_PANEL_EXPANDER_I2C_IO_SDA       (8)
#endif
#endif /* ESP_PANEL_USE_EXPANDER */
```

The issue has been fixed in the new commit. Thank you for testing it!

**Comment by lboue** [comment]
> The issue has been fixed in the new commit. Thank you for testing it!

@Lzw655 I have just redone a test against the latest branch commit and it now works with Waveshare_ESP32_S3_Touch_LCD_4_. I think we can validate this PR. This will make testing easier before releasing the new version.


```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x508
load:0x403c9700,len:0x4
load:0x403c9704,len:0xad0
load:0x403cc700,len:0x29e4
entry 0x403c9880
Squareline WiFi clock example start
Initialize panel device
D (67) ESP_Panel: Panel init start
D (67) ESP_Panel: Use LCD
D (67) ESP_Panel: Use RGB bus
D (68) ESP_Panel: Create LCD bus
D (69) ESP_Panel: Create LCD device
D (72) ESP_Panel: Use touch
D (75) ESP_Panel: Use I2C bus
D (77) ESP_PanelHost: Add host I2C[0]
D (81) ESP_Panel: Create touch bus
D (84) ESP_Panel: Create touch device
D (87) ESP_Panel: Use IO expander
D (90) ESP_Panel: Initialize host
D (94) ESP_PanelHost: Initialize host I2C[0]
D (97) ESP_Panel: Panel init end
D (100) ESP_PanelHost: Destroyed
D (103) ESP_Panel: Panel begin start
D (107) ESP_Panel: Begin IO expander
D (110) ESP_Panel: Begin LCD
D (135) ST7262_CPP: LCD panel @0x3fca8d3c created
D (136) ESP_PanelLcd: Begin start
D (136) ESP_PanelLcd: Begin end
D (136) ESP_Panel: Begin touch
D (137) ESP_PanelBus_I2C: Panel IO @0x3fcaa994 created
D (142) ESP_PanelTouch: Disable interruption
D (146) GT911_CPP: Use default GT911 driver data(address: 0x5d)
I (152) GT911: LCD touch panel create success, version: 1.1.1
W (157) GT911: Unable to initialize the I2C address
I (163) GT911: TouchPad_ID:0x39,0x31,0x31
I (166) GT911: TouchPad_Config_Version:67
D (169) ESP_Panel: Panel begin end
Initialize LVGL
Create UI
wifi_connected_flag: false
                          Squareline WiFi clock example end
```

**Comment by Lzw655** [comment]
@lboue Thank you for your thorough testing. Since the GT911 can set the I2C address using the RST and INT pins, this warning appears if these two pins are not set in the driver. There's no need to worry about it. I'll go ahead and merge this PR.

**Pull request merged**
