### PR TITLE
Add new board Elecrow CrowPanel 7.0"

### PR DESCRIPTION
**Pull request by lboue**
Add new board [Elecrow CrowPanel 7.0"](https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html).

| Feature             | Value| 
|--------------|-----------|
| Main Processor    | ESP32-S3-WROOM-1-N4R8  | 
| FLASH     | 4MB  | 
| PSRAM    | OPI 8MB  | 
| Display Driver      | EK9716BD3 & EK73002ACGB  | 
| Backlight pin     | GPIO2  | 
| Touch Type      | Capacitive Touch  | 
| Touch controller | GT911  |

### CODE REVIEW

**Comment by Lzw655** [comment]
Hi @lboue,

Thanks for your contribution! Is this PR ready for review?

**Comment by lboue** [comment]
> Hi @lboue,
> 
> Thanks for your contribution! Is this PR ready for review?

Not yet, I'm running out of time.

**Comment by lboue** [comment]
Right now I'm trying to fix a problem with the touch controller:
```
Read touch point failed
E (19038) ESP_PanelTouch: readRawData(147): Invalid handle
E (19038) ESP_PanelTouch: readPoints(202): Read raw data failed
Read touch point failed
E (19079) ESP_PanelTouch: readRawData(147): Invalid handle
E (19079) ESP_PanelTouch: readPoints(202): Read raw data failed
Read touch point failed
E (19120) ESP_PanelTouch: readRawData(147): Invalid handle
E (19120) ESP_PanelTouch: readPoints(202): Read raw data failed
```

**Comment by Lzw655** [comment]
Could you please activate the debug log and then share the entire log with me?

**Comment by NecroMancer05** [comment]
Hi @Lzw655 . Thanks for this awesome contribution!

Im using the same dev board (CrowPanel 7.0") i just tried your PR and make it work sucessfully.

Touch is not working because you set controller name wrong the board using GT911 not GT1151 i changed it in CROWPANEL_7_0.h and touch works!

Also sotfware rotation with avoid tearing is not working i solved it with changing width and heigh values:
```
   disp_drv.hor_res = LVGL_PORT_DISP_WIDTH;
   disp_drv.ver_res = LVGL_PORT_DISP_HEIGHT
```;
to:
```
    disp_drv.ver_res = LVGL_PORT_DISP_WIDTH;
    disp_drv.hor_res = LVGL_PORT_DISP_HEIGHT;
```
idk why but this fixed the problem.

**Comment by lboue** [comment]
> Hi @Lzw655 . Thanks for this awesome contribution!
> 
> Im using the same dev board (CrowPanel 7.0") i just tried your PR and make it work sucessfully.
> 
> Touch is not working because you set controller name wrong the board using GT911 not GT1151 i changed it in CROWPANEL_7_0.h and touch works!

Thanks, I'll fix that.

**Comment by lboue** [comment]
> Could you please activate the debug log and then share the entire log with me?

Here is the debug log:
[CrowPanel_ESP32-7_0.log](https://github.com/user-attachments/files/16113654/CrowPanel_ESP32-7_0.log)

**Comment by lboue** [comment]
> Hi @Lzw655 . Thanks for this awesome contribution!
> 
> Im using the same dev board (CrowPanel 7.0") i just tried your PR and make it work sucessfully.
> 
> Touch is not working because you set controller name wrong the board using GT911 not GT1151 i changed it in CROWPANEL_7_0.h and touch works!

@NecroMancer05
I fixed it with commit [d8f3b82](https://github.com/esp-arduino-libs/ESP32_Display_Panel/pull/59/commits/d8f3b82a74a03b7caf33b2211d5b6a8c0784f25c).
Could you share the binary file because it down't work for me?

image

**Comment by NecroMancer05** [comment]
Hi @lboue, i just tried it on consumer product application so i cant share it but i will share a demo app in free time asap.

**Comment by Lzw655** [comment]
> Hi @lboue. Thanks for this awesome contribution!
> 
> Im using the same dev board (CrowPanel 7.0") i just tried your PR and make it work sucessfully.
> 
> Touch is not working because you set controller name wrong the board using GT911 not GT1151 i changed it in CROWPANEL_7_0.h and touch works!
> 
> @Lzw655 Also software rotation with avoid tearing is not working i solved it with changing width and height values:
> 
> ```
>    disp_drv.hor_res = LVGL_PORT_DISP_WIDTH;
>    disp_drv.ver_res = LVGL_PORT_DISP_HEIGHT;
> ```
> 
> to:
> 
> ```
>     disp_drv.ver_res = LVGL_PORT_DISP_WIDTH;
>     disp_drv.hor_res = LVGL_PORT_DISP_HEIGHT;
> ```
> 
> idk why but this fixed the problem.

Hi @NecroMancer05, 

Thank you for pointing out this issue. I will fix it.

**Comment by Lzw655** [comment]
Hi @lboue, 

I checked the schematic of [Elecrow CrowPanel 7.0"](https://www.elecrow.com/esp32-display-7-inch-hmi-display-rgb-tft-lcd-touch-screen-support-lvgl.html) and your configuration file. I found the TP INT pin (IO38_D) is not set. But the I2C address of GT911 is decided by the INT pin, as below.

image

To set the GT911 I2C address to 0x5D (7-bit address, default in the library), we should set the INT pin (IO38_D) to low level before initialize the touch device. You can refer to the [code](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/293faff58c65b1a6e03f34b13b4b513e71b8e408/src/board/espressif/ESP32_S3_BOX_3.h#L196) to do it.

**Comment by lboue** [comment]
> To set the GT911 I2C address to 0x5D (7-bit address, default in the library), we should set the INT pin (IO38_D) to low level before initialize the touch device. You can refer to the [code](https://github.com/esp-arduino-libs/ESP32_Display_Panel/blob/293faff58c65b1a6e03f34b13b4b513e71b8e408/src/board/espressif/ESP32_S3_BOX_3.h#L196) to do it.

Yes, that's what I found with a scan of the I2c addresses:
```
Scanning...
I2C device found at address 0x5D  !
```

**Comment by lboue** [comment]
@Lzw655
Do you know why  `INTE ` pin is also connected to PCA9557 I/O Expander pin 7?
image

**Comment by Lzw655** [comment]
Hi @lboue,

Sorry,[ the schematic](https://www.elecrow.com/download/product/ESP32_Display/7.0inch/ESP32_Dispaly_7.0_module-SCH+PCB_schematic.zip) I saw doesn't include the PCA9557.

**Comment by lboue** [comment]
I used the one found in the manufacturer answer on the forum.
https://forum.elecrow.com/index.php?p=/discussion/760/pdf-version-of-the-crowpanel-7-0-hmi-esp32-display-schematic-file

I have hardware revision V2.1 and not V2.0.
This makes me wonder because I can't find the entender on an I2C scan.

**Comment by lboue** [comment]
> Sorry,[ the schematic](https://www.elecrow.com/download/product/ESP32_Display/7.0inch/ESP32_Dispaly_7.0_module-SCH+PCB_schematic.zip) I saw doesn't include the PCA9557.

You're right. I didn't use the right one. In the manufacturer's response on the forum. I have hardware revision V2.1 and not V2.0. I'll ask them to see if there's a difference.

**Comment by lboue** [comment]
@Lzw655 
How can I fix the [pre-commit](https://github.com/esp-arduino-libs/ESP32_Display_Panel/actions/runs/9846512380/job/27184438391?pr=59)
 job?

**Comment by Lzw655** [comment]
> @Lzw655 How can I fix the CICD [pre-commit](https://github.com/esp-arduino-libs/ESP32_Display_Panel/actions/runs/9846512380/job/27184438391?pr=59) job?

Have you installed 'pre-commit'? You can do this by running the command below:

```bash
pip3 install pre-commit && pre-commit install
```

After that, run the following command to check the rules. If no unexpected changes occur, please add them to Git and commit.

```bash
pre-commit run --all-files
```

**Comment by lboue** [comment]
@Lzw655 It works on my laptop:
```
user@Matter:~/Documents/ESP32_Display_Panel$ pre-commit run --all-files
astyle formatter.........................................................Passed
Check copyright notices..................................................Passed
flake8...................................................................Passed
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for merge conflicts................................................Passed
mixed line ending........................................................Passed
Update when configuration files change...................................Passed
Update when versions change..............................................Passed
```

**Pull request closed without merging**
