### PR TITLE
feat(conf): add versions for all configuration files

### PR DESCRIPTION
**Pull request by Lzw655**

### CODE REVIEW

**Comment by Lzw655** [comment]
Hi @lboue, could you please help me test this new feature and check if your project can compile properly on this branch?

**Comment by lboue** [comment]
I'm going to try this

**Comment by lboue** [comment]
It seems build is OK:

```
Creating esp32s3 image...
Merged 2 ELF sections
Successfully created esp32s3 image.
```

[ESP32_Display_Panel_RGB.ino_build-0.1.3.log](https://github.com/esp-arduino-libs/ESP32_Display_Panel/files/15417605/ESP32_Display_Panel_RGB.ino_build-0.1.3.log)

**Comment by Lzw655** [comment]
Great! Thank you for testing. I will merge it.

**Pull request merged**
